# Generated by Django 3.1.2 on 2020-11-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_validate',
        ),
    ]
